### ISSUE TITLE
Planned restructuring of rules

### ISSUE THREAD

**Issue by foonathan** [foonathan/lexy#10]
Hey all, this is an FYI that I'm planning to restructure how rules, patterns, and branches work.
The new model will be easier to understand, more consistent and more powerful.

## Phase 1: Tokens and Branches (done)

- [x] Replace the `Atom` concept with a new `Token` concept.  Conceptually, it represents an atomic parse unit. This is then used to implement all atomic rules, from like `dsl::lit`.
- [x] Introduce a `dsl::token()` rule that takes an arbitrary rule and turns it into a token replacing `dsl::match()`.
- [x] Implement rules such as `dsl::try_`, `dsl::capture()` and `operator!` on top of tokens only, instead of arbitrary rules/patterns.
- [x] Add a new `Branch` concept that generalizes the existing use of `Pattern` as branches. This also allows turning rules like `dsl::capture()` into branches.
- [x] Eliminate the concept of `Pattern` as it is now unnecessary.

The advantages:

- The token interface is simpler and does not require the use of `LEXY_FORCE_INLINE` as the function names are shorter. This should speed up compilation.
- There is no longer a (at times) inconsistent distinction between rules and patterns. By default, all branch conditions are essentially `LL(k)`.
- The way `Branch` separates matching and value production allows the branch condition to produce actual values. They are only produced after the branch has taken
- Ability to generate parse trees once an `.token()` hook has been added to a parser.

The breaking changes:

- Some rules are no longer usable as branch conditions, but they were before. This can be fixed using `dsl::token()`.
- Some rules previously worked with arbitrary patterns but now require tokens. This can also be fixed using `dsl::token()`.

## Phase 2: Whitespace (done)

The goal is to move away from explicitly specifying whitespace at every point to just tell the grammar what whitespace is and have it be skipped automatically. Note that this is optional: if there are few and very explicit cases where whitespace should be skipped, it can still be done manually.

- [x] Improve `lexy::parse_context` to remember more metadata about the current production.
- [x] Add `dsl::whitespace(rule)` that explicitly skips `rule` as whitespace. It is not a branch.
- [x] Add ability to specify whitespace in the entry production and a way for certain productions to opt-out.
- [x] Add `dsl::whitespace` that automatically skips the computed whitespace.
- [x] Implicitly parse `dsl::whitespace` after every token and production that opted-out of whitespace parsing.
- [x] Remove `operator[]` overloads.
